### ISSUE TITLE
 ImportError: libcusolver.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by pseudotensor** [rapidsai/cugraph#1717]
Ever since updating from 21.08 nightly from 210702 -> 210713 I've hit this problem for all cugraph tests.  cugraph won't even import.

In browsing the internet, tensorflow and other packages have been hit by this issue.  Any insights?

I can install, on ubuntu, this old libcusolver 10, but it shouldn't be needed.  However, then it complains it can't find libcuda.so.1, and it only works after if I point LD_LIBRARY_PATH to pick up `/usr/local/cuda-11.2/compat/libcuda.so.1` , but that breaks other things.

```
[2021-07-15T15:58:26.117Z] CRITICAL: tests/cugraph/dask/test_mg_utility.py
[2021-07-15T15:58:26.117Z] ------------------------------------------------------------------------------
[2021-07-15T15:58:26.117Z] ImportError while importing test module '/h2oai/tests/cugraph/dask/test_mg_utility.py'.
[2021-07-15T15:58:26.117Z] Hint: make sure your test modules/packages have valid Python names.
[2021-07-15T15:58:26.117Z] Traceback:
[2021-07-15T15:58:26.117Z] /opt/h2oai/dai/python/lib/python3.8/importlib/__init__.py:127: in import_module
[2021-07-15T15:58:26.117Z]     return _bootstrap._gcd_import(name[level:], package, level)
[2021-07-15T15:58:26.117Z] tests/cugraph/dask/test_mg_utility.py:14: in <module>
[2021-07-15T15:58:26.117Z]     import cugraph.dask as dcg
[2021-07-15T15:58:26.117Z] /opt/h2oai/dai/python/lib/python3.8/site-packages/cugraph/__init__.py:14: in <module>
[2021-07-15T15:58:26.117Z]     from cugraph.community import (
[2021-07-15T15:58:26.117Z] /opt/h2oai/dai/python/lib/python3.8/site-packages/cugraph/community/__init__.py:14: in <module>
[2021-07-15T15:58:26.117Z]     from cugraph.community.louvain import louvain
[2021-07-15T15:58:26.117Z] /opt/h2oai/dai/python/lib/python3.8/site-packages/cugraph/community/louvain.py:14: in <module>
[2021-07-15T15:58:26.117Z]     from cugraph.community import louvain_wrapper
[2021-07-15T15:58:26.117Z] E   ImportError: libcusolver.so.10: cannot open shared object file: No such file or directory
[2021-07-15T15:58:26.117Z] 

```

**Comment by pseudotensor** [comment]
Note that no other cudf, dask-cuda, etc. hit this same error during import.

```
bash-4.2# conda list | grep 'nvidia\|cu\|rapids'
arrow-cpp                 4.0.1           py38hf0991f3_4_cuda    conda-forge
arrow-cpp-proc            3.0.0                      cuda    conda-forge
cmake_setuptools          0.1.3                      py_0    rapidsai
cudatoolkit               11.2.72              h2bc3f7f_0    nvidia
cudf                      21.08.00a210713 cuda_11.2_py38_g3ed87f3cf3_270    rapidsai-nightly
cudf_kafka                21.08.00a210713 py38_g3ed87f3cf3_270    rapidsai-nightly
cudnn                     8.1.0.77             h90431f1_0    conda-forge
cugraph                   21.08.00a210713 py38_g7ad8fc36_79    rapidsai-nightly
cuml                      21.08.00a210713 cuda11.2_py38_gc9abba1a4_113    rapidsai-nightly
cupy                      9.0.0            py38ha69542f_0    conda-forge
cupy-cuda112              9.0.0                    pypi_0    pypi
curl                      7.77.0               hea6ffbf_0    conda-forge
cusignal                  21.08.00a210713 py38_gb704464_21    rapidsai-nightly
cuspatial                 21.08.00a210713 py38_g8c31c2c_22    rapidsai-nightly
custreamz                 21.08.00a210713 py38_g3ed87f3cf3_270    rapidsai-nightly
cutensor                  1.2.2.5              h96e36e3_3    conda-forge
cuxfilter                 21.08.00a210713 py38_g652bf1c_16    rapidsai-nightly
dask-cuda                 21.08.00a210713         py38_34    rapidsai-nightly
dask-cudf                 21.08.00a210713 py38_g3ed87f3cf3_270    rapidsai-nightly
docutils                  0.17.1                   pypi_0    pypi
faiss-proc                1.0.0                      cuda    rapidsai
icu                       68.1                 h58526e2_0    conda-forge
libcudf                   21.08.00a210713 cuda11.2_g3ed87f3cf3_270    rapidsai-nightly
libcudf_kafka             21.08.00a210713 g3ed87f3cf3_270    rapidsai-nightly
libcugraph                21.08.00a210713 cuda11.2_g7ad8fc36_79    rapidsai-nightly
libcuml                   21.08.00a210713 cuda11.2_gc9abba1a4_113    rapidsai-nightly
libcumlprims              21.08.00a210605 cuda11.2_g8d4e6b0_2    rapidsai-nightly
libcurl                   7.77.0               h2574ce0_0    conda-forge
libcuspatial              21.08.00a210713 cuda11.2_g8c31c2c_22    rapidsai-nightly
libfaiss                  1.7.0           cuda112h5bea7ad_8_cuda    conda-forge
librmm                    21.08.00a210713 cuda11.2_geb2b991_34    rapidsai-nightly
ncurses                   6.2                  he6710b0_1  
pyarrow                   4.0.1           py38hb53058b_4_cuda    conda-forge
rapids                    21.08.00a210709 cuda11.2_py38_g6430beb_23    rapidsai-nightly
rapids-blazing            21.08.00a210709 cuda11.2_py38_g6430beb_23    rapidsai-nightly
rmm                       21.08.00a210712 cuda_11.2_py38_geb2b991_34    rapidsai-nightly
torch                     1.9.0+cu111              pypi_0    pypi
torchvision               0.10.0+cu111             pypi_0    pypi
ucx                       1.9.0+gcd9efd3       cuda11.2_0    rapidsai
ucx-proc                  1.0.0                       gpu    rapidsai
ucx-py                    0.21.0a210713   py38_gcd9efd3_29    rapidsai-nightly
```

**Comment by pseudotensor** [comment]
I solved by using an ubuntu package and installing that old lib.  Shouldn't be required, but ok...
