### ISSUE TITLE
[BUG] try to follow the tutorial for multi-GPU using dask, but failed at the step of dask_cugraph.pagerank()

### ISSUE THREAD

**Issue by han-jiang-etsy** [rapidsai/cugraph#2469]
**Describe the bug**
I am learning how to use cugraph.dask by following this [tutorial ](https://docs.rapids.ai/api/cugraph/nightly/api_docs/dask-cugraph.html). But it failed at the dask_cugraph.pagerank(G, tol=1e-4) step.

**Steps/Code to reproduce bug**
```python
import time
from dask.distributed import Client, wait
import dask_cudf
from dask_cuda import LocalCUDACluster
import cugraph.dask as dcg
import cugraph
from cugraph.comms import comms as Comms
import cugraph
import cudf
import pandas as pd

# init
cluster = LocalCUDACluster(threads_per_worker=1)
client = Client(cluster)

# dummy data
df = pd.DataFrame({'src': [1, 1, 2, 3],
                   'dst': [2, 3, 4, 4],
                   "value":[1, 1, 1, 1],
                   })
input_file = "dummy.csv"
df.to_csv(input_file, index=False, header=False, sep="\t")

chunksize = dcg.get_chunksize(input_file)
e_list = dask_cudf.read_csv(input_file, chunksize = chunksize, delimiter='\t',
                    names=['src', 'dst', "value"], dtype=['int32', 'int32', "float64"])
G_dask = cugraph.DiGraph()
G_dask.from_dask_cudf_edgelist(e_list, source='src', destination='dst', edge_attr="value")
pr_df = dcg.pagerank(G_dask, tol=1e-4)
```
The error is 

```
distributed.core - ERROR - unhashable type: 'dict'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 572, in handle_stream
    handler(**merge(extra, msg))
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 3656, in update_graph_hlg
    annotations,
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 3859, in update_graph
    w = self.coerce_address(w)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 6118, in coerce_address
    if addr in parent._aliases:
TypeError: unhashable type: 'dict'
distributed.core - ERROR - Exception while handling op register-client
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 500, in handle_comm
    result = await result
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4492, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 572, in handle_stream
    handler(**merge(extra, msg))
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 3656, in update_graph_hlg
    annotations,
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 3859, in update_graph
    w = self.coerce_address(w)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 6118, in coerce_address
    if addr in parent._aliases:
TypeError: unhashable type: 'dict'
tornado.application - ERROR - Exception in callback functools.partial(<function TCPServer._handle_connection.<locals>.<lambda> at 0x7fbba26273b0>, <Task finished coro=<BaseTCPListener._handle_stream() done, defined at /opt/conda/lib/python3.7/site-packages/distributed/comm/tcp.py:459> exception=TypeError("unhashable type: 'dict'")>)
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/tornado/ioloop.py", line 741, in _run_callback
    ret = callback()
  File "/opt/conda/lib/python3.7/site-packages/tornado/tcpserver.py", line 331, in <lambda>
    gen.convert_yielded(future), lambda f: f.result()
  File "/opt/conda/lib/python3.7/site-packages/distributed/comm/tcp.py", line 476, in _handle_stream
    await self.comm_handler(comm)
  File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 500, in handle_comm
    result = await result
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 4492, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/opt/conda/lib/python3.7/site-packages/distributed/core.py", line 572, in handle_stream
    handler(**merge(extra, msg))
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 3656, in update_graph_hlg
    annotations,
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 3859, in update_graph
    w = self.coerce_address(w)
  File "/opt/conda/lib/python3.7/site-packages/distributed/scheduler.py", line 6118, in coerce_address
    if addr in parent._aliases:
TypeError: unhashable type: 'dict'
---------------------------------------------------------------------------
CancelledError                            Traceback (most recent call last)
<ipython-input-109-8b6f48b6aa06> in <module>
      4 G_dask = cugraph.DiGraph()
      5 G_dask.from_dask_cudf_edgelist(e_list, source='src', destination='dst', edge_attr="value")
----> 6 pr_df = dcg.pagerank(G_dask, tol=1e-4)

/opt/conda/lib/python3.7/site-packages/cugraph/dask/link_analysis/pagerank.py in pagerank(input_graph, alpha, personalization, max_iter, tol, nstart)
    131      vertex_partition_offsets) = shuffle(input_graph, transposed=True)
    132     num_edges = len(ddf)
--> 133     data = get_distributed_data(ddf)
    134 
    135     if personalization is not None:

/opt/conda/lib/python3.7/site-packages/cugraph/dask/common/input_utils.py in get_distributed_data(input_ddf)
    214     ddf = input_ddf
    215     comms = Comms.get_comms()
--> 216     data = DistributedDataHandler.create(data=ddf)
    217     if data.worker_info is None and comms is not None:
    218         data.calculate_worker_and_rank_info(comms)

/opt/conda/lib/python3.7/site-packages/cugraph/dask/common/input_utils.py in create(cls, data, client)
     91             raise Exception("Graph data must be dask-cudf dataframe")
     92 
---> 93         gpu_futures = client.sync(_extract_partitions, data, client)
     94         workers = tuple(OrderedDict.fromkeys(map(lambda x: x[0], gpu_futures)))
     95         return DistributedDataHandler(gpu_futures=gpu_futures, workers=workers,

/opt/conda/lib/python3.7/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    837         else:
    838             return sync(
--> 839                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    840             )
    841 

/opt/conda/lib/python3.7/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    338     if error[0]:
    339         typ, exc, tb = error[0]
--> 340         raise exc.with_traceback(tb)
    341     else:
    342         return result[0]

/opt/conda/lib/python3.7/site-packages/distributed/utils.py in f()
    322             if callback_timeout is not None:
    323                 future = asyncio.wait_for(future, callback_timeout)
--> 324             result[0] = yield future
    325         except Exception as exc:
    326             error[0] = sys.exc_info()

/opt/conda/lib/python3.7/site-packages/tornado/gen.py in run(self)
    760 
    761                     try:
--> 762                         value = future.result()
    763                     except Exception:
    764                         exc_info = sys.exc_info()

CancelledError: 
```

**Expected behavior**
Not sure why it failed, as I tested on the regular cugraph pagerank and it worked
```
# non-dask success
gdf = cudf.read_csv(input_file, delimiter='\t', names=['src', 'dst', 'value'], dtype=['int32', 'int32', 'float32'])
G1 = cugraph.DiGraph()
G1.from_cudf_edgelist(gdf, source='src', destination='dst', edge_attr="value")
page = cugraph.pagerank(G1, max_iter=40)
```
**Environment overview (please complete the following information)**
 - Environment location: [GCP]
 - Method of cuGraph install: [pre-installed in the docker container]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used

**Environment details**
Please run and paste the output of the `cugraph/print_env.sh` script here, to gather any other relevant environment details
RAPIDS 0.18 (with Intel® MKL-DNN/MKL)
Environment version: M65
Machine type: a2-highgpu-2g (Accelerator Optimized: 2 NVIDIA Tesla A100 GPUs, 24 vCPUs, 170GB RAM)
GPU:NVIDIA Tesla A100 x 2

**Additional context**

**Comment by jnke2016** [comment]
@han-jiang-etsy May I know the cugraph version you are running? Because depending on the `cugraph` version you are running, the location of the comms differ. In `cugraph-22.06` and above the `comms` are located in `cugraph.dask.comms` instead.  Below are few things you are missing:

1. Setting up the `comms` with `Comms.initialize(p2p=True)` right after setting up the client
2. Our current Pagerank implementation doesn't support weights so it needs to be dropped from the edgelist dataframe
3. Destroying the comms, closing both the client and the cluster at the end.

Below is a slightly revised version of your script. I tested it on `cugraph 22.08`

```
import time
from dask.distributed import Client, wait
import dask_cudf
from dask_cuda import LocalCUDACluster
import cugraph.dask as dcg
import cugraph
from cugraph.dask.comms import comms as Comms
import cugraph
import cudf
import pandas as pd

def setup():
    cluster = LocalCUDACluster(threads_per_worker=1)
    client = Client(cluster)
    Comms.initialize(p2p=True)
    return (client, cluster)

def teardown(client, cluster=None):
    Comms.destroy()
    client.close()
    if cluster:
        cluster.close()

# init
if __name__ == '__main__':
    
    # setting up the cluster
    setup_objs = setup()

    # dummy data
    df = pd.DataFrame({'src': [1, 1, 2, 3],
                    'dst': [2, 3, 4, 4],
                    })
    input_file = "dummy.csv"
    df.to_csv(input_file, index=False, header=False, sep="\t")

    chunksize = dcg.get_chunksize(input_file)
    e_list = dask_cudf.read_csv(input_file, chunksize = chunksize, delimiter='\t',
                        names=['src', 'dst'], dtype=['int32', 'int32'])

    G_dask = cugraph.DiGraph()
    G_dask.from_dask_cudf_edgelist(e_list, source='src', destination='dst')
    pr_df = dcg.pagerank(G_dask, tol=1e-4)

    # tearing fown the cluster
    teardown(*setup_objs)
```

**Comment by han-jiang-etsy** [comment]
I tested it on GCP with the image of RAPIDS 0.18 (with Intel® MKL-DNN/MKL) and the cuGraph.__version__ is '0.18.0a+301.g0cc951f7.dirty'

**Comment by jnke2016** [comment]
Ok. That version is very old

**Comment by han-jiang-etsy** [comment]
@jnke2016 no worry. I tested your code and it produced the same error on my end. Since the GCP suggested to use this  0.18 as the development environment based on this [article](https://cloud.google.com/blog/products/ai-machine-learning/scale-model-training-in-minutes-with-rapids-dask-nvidia-gpus). I wonder what would be your suggestion for creating the environment using the latest version on GCP.

**Comment by jnke2016** [comment]
@han-jiang-etsy I will recommend using our latest stable cugraph version which is currently `22.06`. Even though the version is different, the API is pretty consistent throughout our releases. One of the few breaking changes we made for instance was the location of the `comms`. You can build `cuGraph` either with `conda` or from `source`

**Comment by han-jiang-etsy** [comment]
@jnke2016 thank you so much. I am try that and will keep you in the loop. all the best

**Comment by han-jiang-etsy** [comment]
I have updated to the 22.06 and the issue resolved
